[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.1.0"
license = "LicenseRef-DCL-1.0"
homepage = "https://github.com/rainlanguage/rain.math.float.deploy"
repository = "https://github.com/rainlanguage/rain.math.float.deploy"

[workspace.dependencies]
alloy = { version = "1.0.9", default-features = false, features = [
  "sol-types",
  "json",
  "json-abi",
] }
revm = { version = "36", default-features = false, features = [
  "portable",
  "std",
  "tracer",
] }
thiserror = "2.0.12"
proptest = "1.7.0"
serde = "1.0.219"
